# MergeSort

<div style="direction: rtl;">
     الگوریتم مرتب سازی ادغامی بر اساس روش تقسیم و غلبه کار می کند
  <ol>
    <li>در صورتی که تنها یک عنصر در آرایه باشد آرایه از قبل مرتب است و برگشت داده می شود</li>
    <li>ابتداد اندیس وسط آرایه بدست می آید</li>    
    <li> سپس آرایه به دو قسمت مساوی با توجه به اندیس میانی تقسیم می شود </li>
    <li>هر بخش به صورت جداگانه و به صورت بازگشتی با فراخوانی تابع مرتب سازی ادغامی مرتب می شود</li>
    <li>
        <p style="text-align: right;" >  
            زیرآرایه های مرتب شده با یکدیگر ادغام م شوند تا یک آرایه کامل و مرتب شده ایجاد شود
          </br>
      فرایند ادغام دو زیرآرایه مرتب شده به این صورت انجام می شود که ابتدا عناصر دو زیرآرایه با هم مقایسه می شوند و کمترین عنصر را در ابتدای آرایه ادغامی قرار می دهیم. سپس به طور مرتب ادامه می دهیم و عناصر بعدی را با یکدیگر مقایسه کرده و کمترین عنصر را در آرایه ادغامی قرار می دهیم. این فرآیند تا زمانی ادامه پیدا می کند که تمام عناصر دو زیرآرایه در آرایه ادغامی قرار گیرند. در نهایت، آرایه ادغامی به صورت کامل مرتب و حاوی تمام عناصر از دو زیرآرایه است.
        </p>
        </li>
  </ol>
   <p style="text-align: right;" >   زمان اجرای این الگوریتم O(nLog(n) می باشد</p>
</div>

In [25]:
import numpy as np

# Example usage:
numbers = np.array([9,1.0, 4.0, 5.0, 6.0, 0.5, 8.0, -1.0, -0.5, 6.0, 8.0])

print("Original array:", numbers)

#sort inplace= false
sorted_numbers =np.sort(numbers ,kind="mergesort")

print("Sorted array in ascending order:", sorted_numbers)

#sort inplace= true
print("Original array:", numbers)
numbers.sort(kind="mergesort")
print("Sorted array in ascending order:", numbers)
print("Original array changed:", numbers)


Original array: [ 9.   1.   4.   5.   6.   0.5  8.  -1.  -0.5  6.   8. ]
Sorted array in ascending order: [-1.  -0.5  0.5  1.   4.   5.   6.   6.   8.   8.   9. ]
Original array: [ 9.   1.   4.   5.   6.   0.5  8.  -1.  -0.5  6.   8. ]
Sorted array in ascending order: [-1.  -0.5  0.5  1.   4.   5.   6.   6.   8.   8.   9. ]
Original array changed: [-1.  -0.5  0.5  1.   4.   5.   6.   6.   8.   8.   9. ]


In [1]:
import numpy as np


def merge_sort (arr) :
    if arr.shape[0]<=1:
        #print ("return  : " ,arr)
        return arr

    # Find the middle index of the list
    mid = arr.shape[0] // 2

    # Divide the list into two halves recursively
    left = arr[:mid]
    #print("left_arr :" , left)
    right = arr[mid:]
    #print("right_arr :" , right)
    
    #print("call merge_sort on left_arr :" ,left)
    left_arr = merge_sort(left)
    
    #print("call merge_sort on right_arr :" ,right)
    right_arr = merge_sort(right)
    
    # Merge the two sorted halves
    return merge(left_arr, right_arr)


def merge(left, right):
    #print("Call merge on ",left ,"|" , right)
    if len(left) == 0:
        return right
    if len(right) == 0:
        return left
    
    if left[0] < right[0]:
        merged = np.concatenate(([left[0]], merge(left[1:], right)))
    else:
        merged = np.concatenate(([right[0]], merge(left, right[1:])))
    #print ("sorted & merged : ",merged )
    return merged




numbers = np.array([9,1.0, 4.0, 5.0, 6.0, 0.5, 8.0, -1.0, -0.5, 6.0, 8.0])
print("Original array:", numbers)
sorted_numbers = merge_sort(numbers)
print("Sorted array in ascending order:", sorted_numbers)

Original array: [ 9.   1.   4.   5.   6.   0.5  8.  -1.  -0.5  6.   8. ]
Sorted array in ascending order: [-1.  -0.5  0.5  1.   4.   5.   6.   6.   8.   8.   9. ]


# QuickSort



<div style="direction: rtl;">
     الگوریتم مرتب سازی سریع بر اساس روش تقسیم و غلبه کار می کند
  <ol>
    <li>ابتدا یک عنصر به عنوان Pivot انتخاب می شود این عنصر می تواند وسط ، ایتدا  یا انتهای آرایه باشد</li>
      <li> <p style="text-align: right;" >
          سپس آرایه به دو زیر آرایه تقسیم می شود</p> </li>
      یک زیر آرایه حاوی عناصر کوچکتر از پیوت و یک زیر آرایه با عناصر بزرگتر  پیوت
      این عمل با مقایسه عناصر آرایه با پیوت انجام می شود
    <li>
        <p style="text-align: right;" >
            به صورت بازگشتی الگوریتم مرتب سازی سریع برای هر یک از زیر آرایه ها تکرار می شود 
      </br>
      این عمل آنقدر تکرار می شود تا آرایه به زیر آرایه کوچکتر تقسیم نشود 
        </p>  
    </li>
    <li>
        <p style="text-align: right;" >           
            وقتی زیر آرایه ها به طور جداگانه مرتب شوند آرایه با ترکیب  دو زیر آرایه مرتب شده ، مرتب می کنیم
        </br>
            بدین صورت که ابتدا آرایه با عناصر کوچک تر از محور سپس عنصر محور و یعد از آن آرایه با عناصر بزرگتر از محور            
        </p>
     </li>
  </ol>
  
  <p style="text-align: right;" >  
    زمان اجرا الگوریتم به صورت متوسط O(nlogn) است
   </br>
   در بدتربن حالت یعنی در صورتی که پیوت برابر با بزرگترین یا کوچکترین عنصر آرایه باشد زمان اجرا O(n^2) است 
  </p>
</div>


In [16]:
import numpy as np

# Example usage:
numbers = np.array([9,1.0, 4.0, 5.0, 6.0, 0.5, 8.0, -1.0, -0.5, 6.0, 8.0])

print("Original array:", numbers)
#sort inplace= false
sorted_numbers =np.sort(numbers ,kind="quicksort")

print("Sorted array in ascending order:", sorted_numbers)

#sort inplace= true
print("Original array:", numbers)
numbers.sort(kind="quicksort")
print("Sorted array in ascending order:", numbers)
print("Original array changed:", numbers)


Original array: [ 9.   1.   4.   5.   6.   0.5  8.  -1.  -0.5  6.   8. ]
Sorted array in ascending order: [-1.  -0.5  0.5  1.   4.   5.   6.   6.   8.   8.   9. ]
Original array: [ 9.   1.   4.   5.   6.   0.5  8.  -1.  -0.5  6.   8. ]
Sorted array in ascending order: [-1.  -0.5  0.5  1.   4.   5.   6.   6.   8.   8.   9. ]
Original array changed: [-1.  -0.5  0.5  1.   4.   5.   6.   6.   8.   8.   9. ]


In [18]:
import numpy as np
def quick_sort(arr):
    if len(arr) <= 1:
        return arr

    pivot = arr[len(arr) // 2]
    less = arr[arr < pivot]
    equal= arr[arr == pivot]
    greater = arr[arr> pivot]
    
    return np.concatenate((quick_sort(less), equal, quick_sort(greater)))


# Example usage:
numbers = np.array([9,1.0, 4.0, 5.0, 6.0, 0.5, 8.0, -1.0, -0.5, 6.0, 8.0])
print("Original array:", numbers)
sorted_numbers = quick_sort(numbers)
print("Sorted array in ascending order:", sorted_numbers)



Original array: [ 9.   1.   4.   5.   6.   0.5  8.  -1.  -0.5  6.   8. ]
Sorted array in ascending order: [-1.  -0.5  0.5  1.   4.   5.   6.   6.   8.   8.   9. ]
Original array: ['a' 'bc' 'asfs' 'A' '1']
Sorted array in ascending order: ['1' 'A' 'a' 'asfs' 'bc']


# HeapSort


<div style="direction: rtl;">
    <p style="text-align: right;" >
        الگوریتم Heap Sort یک الگوریتم مرتب سازی است که از ساختمان داده هیپ استفاده می کند. این الگوریتم را می توان به سه بخش اصلی تقسیم کرد: ساخت هیپ اولیه، حذف ریشه و بازسازی هیپ.
    </p>
  <ul>
    <li>	ساخت هیپ اولیه:</li>
      <ol>
          <li>آرایه ورودی را به عنوان یک هیپ در نظر می گیریم.</li>
          <li>از آخرین عنصر غیربرگ شروع کرده و هر گره را به ترتیب به سمت بالا پیمایش می کنیم.</li>
          <li>در هر گره، اگر مقدار آن کمتر از یکی از فرزندانش بود، مقادیر را تعویض می کنیم تا خاصیت هیپ حفظ شود.</li>
          <li>این عملیات را بر روی تمام گره ها تا ریشه انجام می دهیم.</li>
          <li>پس از اتمام این مرحله، آرایه به صورت یک هیپ Max ساخته شده است.</li>       
      </ol>
  </ul>
  <ul>
    <li>حذف ریشه:</li>
      <ol>
          <li>ریشه هیپ (که بزرگترین عنصر است) را با آخرین عنصر هیپ جابجا می کنیم.</li>
          <li>آخرین عنصر را از هیپ حذف می کنیم.</li>
          <li>سپس بازسازی هیپ را با ریشه جدید انجام می دهیم تا خاصیت هیپ حفظ شود.</li>          
      </ol>
  </ul>
  <ul>
    <li>بازسازی هیپ:</li>
      <ol>
          <li>از ریشه هیپ شروع کرده و هر گره را به ترتیب به سمت پایین پیمایش می کنیم.</li>
          <li>در هر گره، بین آن و دو فرزندش بزرگترین مقدار را انتخاب می کنیم.</li>
          <li>اگر بزرگترین مقدار در فرزند چپ بود، مقادیر را تعویض می کنیم.</li>
          <li>این عملیات را تا زمانی که گره به صورت صحیح در هیپ قرار گیرد و دیگر فرزندی نداشته باشد، ادامه می دهیم</li>
      </ol>
          
      
  </ul>
 <p style="text-align: right;" >      
مرتب سازی در مرحله حذف ریشه هیپ انجام می شود. هر بار که ریشه هیپ (بزرگترین عنصر) حذف می شود و جایگزین آن با آخرین عنصر هیپ می شود، هیپ باقی مانده دوباره بازسازی می شود تا بزرگترین عنصر در ریشه قرار بگیرد. با تکرار این عملیات بر روی هیپ، آرایه به صورت صعودی مرتب می شود. پس از اتمام عملیات حذف ریشه، آرایه مرتب شده به دست می آید. </p>

</div>




In [26]:
import numpy as np

# Example usage:
numbers = np.array([9,1.0, 4.0, 5.0, 6.0, 0.5, 8.0, -1.0, -0.5, 6.0, 8.0])

print("Original array:", numbers)
#sort inplace= false
sorted_numbers =np.sort(numbers ,kind="heapsort")

print("Sorted array in ascending order:", sorted_numbers)

#sort inplace= true
print("Original array:", numbers)
numbers.sort(kind="quicksort")
print("Sorted array in ascending order:", numbers)
print("Original array changed:", numbers)

Original array: [ 9.   1.   4.   5.   6.   0.5  8.  -1.  -0.5  6.   8. ]
Sorted array in ascending order: [-1.  -0.5  0.5  1.   4.   5.   6.   6.   8.   8.   9. ]
Original array: [ 9.   1.   4.   5.   6.   0.5  8.  -1.  -0.5  6.   8. ]
Sorted array in ascending order: [-1.  -0.5  0.5  1.   4.   5.   6.   6.   8.   8.   9. ]
Original array changed: [-1.  -0.5  0.5  1.   4.   5.   6.   6.   8.   8.   9. ]


In [3]:
import numpy as np

def heapify(arr, n, i):
    max_index = i
    left = 2 * i + 1
    right = 2 * i + 2
    #print("indices",max_index,left,right)
    #print(arr)

    indices = np.array([max_index, left, right])
    valid_indices = indices[indices < n]

    if valid_indices.size > 0:
        max_index = np.argmax(arr[valid_indices])
        max_child = valid_indices[max_index]

        if arr[max_child] > arr[i]:
            arr[i], arr[max_child] = arr[max_child], arr[i]            
            heapify(arr, n, max_child)


def build_max_heap(arr, n, i):
    heapify(arr, n, i)
    if i > 0:
        build_max_heap(arr, n, i - 1)
        
def heap_sort(arr):
    n = arr.size

    if n > 1:
        # Build max heap recursively
        build_max_heap(arr, n, n // 2 - 1)        
        

        # Sort the array recursively
        def sort(arr, n):
            if n > 1:
                arr[0], arr[n-1] = arr[n-1], arr[0]  # Swap
                heapify(arr, n-1, 0)
                sort(arr, n-1)

        sort(arr, n)

 #Example usage
numbers = np.array([9,1.0, 4.0, 5.0, 6.0, 0.5, 8.0, -1.0, -0.5, 6.0, 8.0])
print("Original array:",numbers)

heap_sort(numbers)
print("Sorted array in ascending order:", numbers)

Original array: [ 9.   1.   4.   5.   6.   0.5  8.  -1.  -0.5  6.   8. ]
Sorted array in ascending order: [-1.  -0.5  0.5  1.   4.   5.   6.   6.   8.   8.   9. ]


# Asks user to enter array and sort method

In [4]:

# Example usage:
user_input = input("Enter a list of numbers separated by spaces or commas: ")
numbers = np.array(user_input.replace(',', ' ').split() , dtype=float)
print("Original array:\n", numbers)
  

while True:
    
    arr=numbers.copy()
     
    key = input("Enter a character (M, Q, H) or any other to exit: ")
    
    if key.upper() == "M" :
        s = merge_sort(arr)
        print("MergeSort : Sorted array in ascending order: \n", s,"\n")
    elif key.upper() == "Q" :
        s= quick_sort(arr)
        print("QuickSort : Sorted array in ascending order:\n", s,"\n")
    elif key.upper() == "H" :
        heap_sort(arr)
        print("HeapSort : Sorted array in ascending order:\n", arr,"\n")

    else:       
        print("Exiting...")
        break
        
        

    


Enter a list of numbers separated by spaces or commas: -1,0,-5,-100,0,8,10,4
Original array:
 [  -1.    0.   -5. -100.    0.    8.   10.    4.]
Enter a character (M, Q, H) or any other to exit: Q
QuickSort : Sorted array in ascending order:
 [-100.   -5.   -1.    0.    0.    4.    8.   10.] 

Enter a character (M, Q, H) or any other to exit: H
HeapSort : Sorted array in ascending order:
 [-100.   -5.   -1.    0.    0.    4.    8.   10.] 

Enter a character (M, Q, H) or any other to exit: M
MergeSort : Sorted array in ascending order: 
 [-100.   -5.   -1.    0.    0.    4.    8.   10.] 

Enter a character (M, Q, H) or any other to exit:  
Exiting...
